external_templates:
  pmm: templates
  template_variables:
    default:
      horizontal_align: left
      vertical_align: top
    conditionals:
      vertical_offset:
        default: 5
        conditions:
          - vertical_align: center
            value: 0
          - vertical_align: top
            value: 5
          - vertical_align: bottom
            value: 30
      horizontal_offset:
        default: 205
        conditions:
          - horizontal_align: center
            value: 0
          - horizontal_align: [left, right]
            value: 205
      pmm:
        conditions:
          - file.exists: false
            url.exists: false
            git.exists: false
            repo.exists: false
            value: <<overlay_name>>
    allowed_libraries: movie
    font: fonts/Roboto-Bold.ttf
    font_size: 50
    back_color: "#00000099"
    back_width: 255
    back_height: 105
    final_name: STINGER

overlays:
  Mediastinger:
    template:
      name: standard
    plex_all: true
    filters:
      tmdb_keyword: aftercreditsstinger, duringcreditsstinger