templates:
  IMDB_Ratingred:                                                               #IDMB Rating Logo
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: IMDBRating
      weight: <<weight>>
      horizontal_offset: 530
      horizontal_align: left
      vertical_offset: 10
      vertical_align: bottom
  IMDB1000:                                                                     #IMDB Rating (Top 1000)
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    imdb_list: https://www.imdb.com/search/title/?title_type=feature,tv_movie,documentary&groups=top_1000
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: IMDBRating
      weight: <<weight>>
      horizontal_offset: 530
      horizontal_align: left
      vertical_offset: 10
      vertical_align: bottom
  IMDB250:                                                                      #IMDB Rating Logo (Top 250)
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    imdb_list: https://www.imdb.com/search/title/?title_type=feature,tv_movie,documentary&groups=top_250
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: IMDBRating
      weight: <<weight>>
      horizontal_offset: 530
      horizontal_align: left
      vertical_offset: 10
      vertical_align: bottom
  IMDB100:                                                                      #IMDB Rating Logo (Top 100)
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    imdb_list: https://www.imdb.com/search/title/?title_type=feature,tv_movie,documentary&groups=top_100
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: IMDBRating
      weight: <<weight>>
      horizontal_offset: 530
      horizontal_align: left
      vertical_offset: 10
      vertical_align: bottom

  Audience_Rating:                                                               #Audience Rating Text (IMDB Rating)
    optional:
      - overlay_level
    default:
      rating_type: audience_rating
      horizontal_offset: 679
      horizontal_align: left
      vertical_offset: 33
      vertical_align: bottom
    collection_level: <<overlay_level>>
    overlay:
      name: text(<<rating_type>>)
      horizontal_offset: <<horizontal_offset>>
      horizontal_align: <<horizontal_align>>
      vertical_offset: <<vertical_offset>>
      vertical_align: <<vertical_align>>
      font: config/fonts/Roboto-Bold.ttf
      font_size: 60
      font_color: "#FFFFFF"

  MDB_Rating:                                                                    #MDBList Rating Logo
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      horizontal_offset: 10
      horizontal_align: left
      vertical_offset: 10
      vertical_align: bottom

  User_Rating:                                                                   #User Rating Text (MDBList Score)
    optional:
      - overlay_level
    default:
      rating_type: user_rating
      horizontal_offset: 124
      horizontal_align: left
      vertical_offset: 33
      vertical_align: bottom
    collection_level: <<overlay_level>>
    overlay:
      name: text(<<rating_type>>)
      horizontal_offset: <<horizontal_offset>>
      horizontal_align: <<horizontal_align>>
      vertical_offset: <<vertical_offset>>
      vertical_align: <<vertical_align>>
      font: config/fonts/Roboto-Bold.ttf
      font_size: 60
      font_color: "#FFFFFF"

  RT-Crit-Freshred:                                                            #Rotten Tomatoes Rating Logo (Fresh)
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: RTRating
      weight: <<weight>>
      horizontal_offset: 270
      horizontal_align: left
      vertical_offset: 10
      vertical_align: bottom
  RT-Crit-Rottenred:                                                           #Rotten Tomatoes Rating Logo (Rotten)
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: RTRating
      weight: <<weight>>
      horizontal_offset: 270
      horizontal_align: left
      vertical_offset: 10
      vertical_align: bottom
  RT-CF-Rating:                                                                #Rotten Tomatoes Rating Logo (Certified Fresh)
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    mdblist_list: https://mdblist.com/lists/plexmetamanager/certifiedfreshmovies
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: RTRating
      weight: <<weight>>
      horizontal_offset: 270
      horizontal_align: left
      vertical_offset: 10
      vertical_align: bottom

  Critic_Rating:                                                               #Critic Rating Text (Rotten Tomatoes Rating Under 10)
    optional:
      - overlay_level
    default:
      rating_type: critic_rating
      horizontal_offset: 381
      horizontal_align: left
      vertical_offset: 33
      vertical_align: bottom
    collection_level: <<overlay_level>>
    overlay:
      name: text(<<rating_type>>)
      horizontal_offset: <<horizontal_offset>>
      horizontal_align: <<horizontal_align>>
      vertical_offset: <<vertical_offset>>
      vertical_align: <<vertical_align>>
      font: config/fonts/Roboto-Bold.ttf
      font_size: 60
      font_color: "#FFFFFF"

  Critic_Rating10:                                                             #Critic Rating Text (Rotten Tomatoes Rating 10)
    optional:
      - overlay_level
    default:
      rating_type: critic_rating#
      horizontal_offset: 385
      horizontal_align: left
      vertical_offset: 33
      vertical_align: bottom
    collection_level: <<overlay_level>>
    overlay:
      name: text(<<rating_type>>)
      horizontal_offset: <<horizontal_offset>>
      horizontal_align: <<horizontal_align>>
      vertical_offset: <<vertical_offset>>
      vertical_align: <<vertical_align>>
      font: config/fonts/Roboto-Bold.ttf
      font_size: 60
      font_color: "#FFFFFF"

  IMDbTop250:
    default:
      overlay: <<overlay_name>>
    imdb_chart: top_<<library_type>>s
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      queue: Designation_Queue
      weight: <<weight>>
      horizontal_offset: 0
      horizontal_align: right
      vertical_offset: 0
      vertical_align: bottom
  
  RT-Cert-Fresh:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    mdblist_list: https://mdblist.com/lists/plexmetamanager/certifiedfreshmovies
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      queue: Designation_Queue
      weight: <<weight>>
      horizontal_offset: 0
      horizontal_align: right
      vertical_offset: 0
      vertical_align: bottom
      
  Meta-Must:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    mdblist_list: https://mdblist.com/lists/frostywolf/metacritic-must-see-movies/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      queue: Designation_Queue
      weight: <<weight>>
      horizontal_offset: 0
      horizontal_align: right
      vertical_offset: 0
      vertical_align: bottom


  Oscar:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    imdb_list: https://www.imdb.com/search/title/?groups=oscar_winner
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 10
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top

  Cannes:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list: 
    - https://trakt.tv/users/maxwelldeux/lists/cannes-film-festival-palme-d-or
    - https://trakt.tv/users/maxwelldeux/lists/cannes-film-festival-grand-prix
    - https://trakt.tv/users/sp1ti/lists/cannes-palme-d-or-winners
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 10
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top

  Venice:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list: https://trakt.tv/users/maxwelldeux/lists/venice-film-festival-golden-lion
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 5
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top

  Berlin:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list: 
    - https://trakt.tv/users/maxwelldeux/lists/berlin-international-film-festival-golden-bears
    - https://trakt.tv/users/eloy86/lists/berlin-international-film-festival-golden-bear-winners
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 5
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top

  Sundance:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list:
    - https://trakt.tv/users/maxwelldeux/lists/sundance-film-festival-grand-jury-prize
    - https://trakt.tv/users/sp1ti/lists/sundance-film-festival-grand-jury-prize-dramatic
    - https://trakt.tv/users/sp1ti/lists/sundance-film-festival-grand-jury-prize-documentary
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 10
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top

  golden-globe:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    imdb_list: https://www.imdb.com/search/title/?groups=golden_globe_winner
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 5
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top

  bafta:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list: 
    - https://trakt.tv/users/maxwelldeux/lists/bafta-award-best-film
    - https://trakt.tv/users/ashota/lists/bafta-award-for-best-film
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 5
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top

  saturn:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list: 
    - https://trakt.tv/users/eloy86/lists/saturn-award-for-best-science-fiction-film-winners
    letterboxd_list:
    - https://letterboxd.com/jonny5244/list/saturn-awards/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 5
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top



queues:
  Designation_Queue:
    - horizontal_offset: 0
      horizontal_align: right
      vertical_offset: 0
      vertical_align: bottom
    - horizontal_offset: 0
      horizontal_align: right
      vertical_offset: 230
      vertical_align: bottom
    - horizontal_offset: 0
      horizontal_align: right
      vertical_offset: 460
      vertical_align: bottom

overlays:
  rating_IMDB:
    template:
      - name: IMDB_Ratingred
        weight: 20
    plex_search:
      all:
        audience_rating.gte: 0.1
        audience_rating.lte: 10

  IMDB1000:
    template:
      - name: IMDB1000
        weight: 30

  IMDB250:
    template:
      - name: IMDB250
        weight: 40

  IMDB100:
    template:
      - name: IMDB100
        weight: 50

  audience_rating:
    template:
      name: Audience_Rating
    plex_search:
      all:
        audience_rating.gte: 0.1
        audience_rating.lte: 10

  rating_mdb:
    template:
      - name: MDB_Rating
    plex_search:
      all:
        user_rating.gte: 0.1
        user_rating.lte: 10

  user_rating:
    template:
      name: User_Rating
    plex_search:
      all:
        user_rating.gte: 0.1
        user_rating.lte: 10
  
  rating_Rotten:
    template:
      - name: RT-Crit-Rottenred
        weight: 30
    plex_search:
      all:
        critic_rating.gte: 0.1
        critic_rating.lte: 6.0

  rating_Fresh:
    template:
      - name: RT-Crit-Freshred
        weight: 40
    plex_search:
      all:
        critic_rating.gte: 6.1
        critic_rating.lte: 10

  RT-CF-Rating:
    template:
      - name: RT-CF-Rating
        weight: 50

  critic_rating:
    template:
      name: Critic_Rating
    plex_search:
      all:
        critic_rating.gte: 0.1
        critic_rating.lte: 9.9

  critic_rating10:
    template:
      name: Critic_Rating10
    plex_search:
      all:
        critic_rating.gte: 10
        critic_rating.lte: 10


#  IMDB-Top-250red:
#    template:
#      - name: IMDbTop250
#        weight: 50

  MC-Must-See:
    template:
      - name: Meta-Must
        weight: 45

#  RT-Cert-Freshred:
#    template:
#      - name: RT-Cert-Fresh
#        weight: 40

  Oscarred:
    template:
      - name: Oscar
        weight: 100

  golden-globe:
    template:
      - name: golden-globe
        weight: 90 

  bafta:
    template:
      - name: bafta
        weight: 80

  Palmered:
    template:
      - name: Cannes
        weight: 70

  Berlinalered:
    template:
      - name: Berlin
        weight: 60

  Venicered:
    template:
      - name: Venice
        weight: 50

  saturn:
    template:
      - name: saturn
        weight: 40

  Sundancered:
    template:
      - name: Sundance
        weight: 30