templates:
  IMDB_Ratingred:                                                               #IDMB Rating Logo
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      queue: Rating_Queue_Logo
      weight: <<weight>>
  IMDB250:                                                                      #IMDB Rating Logo (Top 250)
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    imdb_chart: top_shows
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      queue: Rating_Queue_Logo
      weight: <<weight>>
  Audience_Rating:                                                               #Audience Rating Text (IMDB Rating)
    optional:
      - overlay_level
    default:
      rating_type: audience_rating
    collection_level: <<overlay_level>>
    overlay:
      name: text(<<rating_type>>)
      queue: Rating_Queue_Text
      weight: <<weight>>
      font: fonts/Roboto-Bold.ttf
      font_size: 60
      font_color: "#FFFFFF"

  MDB_Rating:                                                                    #MDBList Rating Logo
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      queue: Rating_Queue_Logo
      weight: <<weight>>

  User_Rating:                                                                   #User Rating Text (MDBList Score)
    optional:
      - overlay_level
    default:
      rating_type: user_rating
    collection_level: <<overlay_level>>
    overlay:
      name: text(<<rating_type>>)
      queue: Rating_Queue_Text
      weight: <<weight>>
      font: fonts/Roboto-Bold.ttf
      font_size: 60
      font_color: "#FFFFFF"

  RT-Crit-Freshred:                                                            #Rotten Tomatoes Rating Logo (Fresh)
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      queue: Rating_Queue_Logo
      weight: <<weight>>
  RT-Crit-Rottenred:                                                           #Rotten Tomatoes Rating Logo (Rotten)
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      queue: Rating_Queue_Logo
      weight: <<weight>>
  RT-CF-Rating:                                                                #Rotten Tomatoes Rating Logo (Certified Fresh)
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    mdblist_list: https://mdblist.com/lists/frostywolf/certified-fresh-shows
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      queue: Rating_Queue_Logo
      weight: <<weight>>

  Critic_Rating:                                                               #Critic Rating Text (Rotten Tomatoes Rating Under 10)
    optional:
      - overlay_level
    default:
      rating_type: critic_rating
    collection_level: <<overlay_level>>
    overlay:
      name: text(<<rating_type>>)
      queue: Rating_Queue_Text
      weight: <<weight>>
      font: fonts/Roboto-Bold.ttf
      font_size: 60
      font_color: "#FFFFFF"

  Critic_Rating10:                                                             #Critic Rating Text (Rotten Tomatoes Rating 10)
    optional:
      - overlay_level
    default:
      rating_type: critic_rating#
    collection_level: <<overlay_level>>
    overlay:
      name: text(<<rating_type>>)
      queue: Rating_Queue_Text
      weight: <<weight>>
      font: fonts/Roboto-Bold.ttf
      font_size: 60
      font_color: "#FFFFFF"

  Meta-Must:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    mdblist_list: https://mdblist.com/lists/plexmetamanager/metacriticmustseeshows
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      horizontal_offset: 2
      horizontal_align: right
      vertical_offset: 2
      vertical_align: bottom

queues:
  Rating_Queue_Logo:
    - horizontal_offset: 10
      horizontal_align: left
      vertical_offset: 10
      vertical_align: bottom
    - horizontal_offset: 270
      horizontal_align: left
      vertical_offset: 10
      vertical_align: bottom
    - horizontal_offset: 530
      horizontal_align: left
      vertical_offset: 10
      vertical_align: bottom
  Rating_Queue_Text:
    - horizontal_offset: 159
      horizontal_align: left
      vertical_offset: 33
      vertical_align: bottom
    - horizontal_offset: 424
      horizontal_align: left
      vertical_offset: 33
      vertical_align: bottom
    - horizontal_offset: 679
      horizontal_align: left
      vertical_offset: 33
      vertical_align: bottom

overlays:
  IMDB_Ratingred:
    template:
      - name: IMDB_Ratingred
        weight: 80
    plex_search:
      all:
        audience_rating.gte: 0
        audience_rating.lte: 10

  IMDB250:
    template:
      - name: IMDB250
        weight: 82
    suppress_overlays:
      - IMDB_Ratingred

  audience_rating:
    template:
      name: Audience_Rating
      weight: 80
    plex_search:
      all:
        audience_rating.gte: 0
        audience_rating.lte: 10

  MDB_Rating:
    template:
      - name: MDB_Rating
        weight: 100
    plex_search:
      all:
        user_rating.gte: 0
        user_rating.lte: 10

  user_rating:
    template:
      name: User_Rating
      weight: 100
    plex_search:
      all:
        user_rating.gte: 0
        user_rating.lte: 10
  
  RT-Crit-Rottenred:
    template:
      - name: RT-Crit-Rottenred
        weight: 90
    plex_search:
      all:
        critic_rating.gte: 0
        critic_rating.lte: 6.0

  RT-Crit-Freshred:
    template:
      - name: RT-Crit-Freshred
        weight: 91
    plex_search:
      all:
        critic_rating.gte: 6.1
        critic_rating.lte: 10
    suppress_overlays:
      - RT-Crit-Rottenred

  RT-CF-Rating:
    template:
      - name: RT-CF-Rating
        weight: 92
    suppress_overlays:
      - RT-Crit-Freshred
      - RT-Crit-Rottenred

  critic_rating:
    template:
      name: Critic_Rating
      weight: 90
    plex_search:
      all:
        critic_rating.gte: 0
        critic_rating.lte: 9.9

  critic_rating10:
    template:
      name: Critic_Rating10
      weight: 91
    plex_search:
      all:
        critic_rating.gte: 10
        critic_rating.lte: 10
    suppress_overlays:
      - Critic_Rating

  MC-Must-See:
    template:
      - name: Meta-Must