templates:
  Award:
    optional:
      -overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: <<horizontal_offset>>
      horizontal_align: left
      vertical_offset: <<vertical_offset>>
      vertical_align: top

  Oscar:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    imdb_list: https://www.imdb.com/search/title/?groups=oscar_winner
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 5
      horizontal_align: left
      vertical_offset: 5
      vertical_align: top

  Oscarglow:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list: 
    - https://trakt.tv/users/kingkearney/lists/oscars-best-picture
    - https://trakt.tv/users/jrpetersjr/lists/academy-award-best-picture
    - https://trakt.tv/users/r_lewis/lists/oscars-best-picture-winners
    - https://trakt.tv/users/twentywashere/lists/academy-awards-best-picture
    letterboxd_list:
    - https://letterboxd.com/tajlv/list/best-picture/
    - https://letterboxd.com/jake_ziegler/list/academy-award-winners-for-best-picture/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 2
      horizontal_align: left
      vertical_offset: 2
      vertical_align: top

  Cannes:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list: 
    - https://trakt.tv/users/maxwelldeux/lists/cannes-film-festival-grand-prix
    letterboxd_list:
    - https://letterboxd.com/vinwaters/list/cannes/
    - https://letterboxd.com/antoniorojo/list/cannes/
    - https://letterboxd.com/ihatejungles/list/cannes/
    - https://letterboxd.com/vinwaters/list/cannes/
    - https://letterboxd.com/feelinglistless/list/cannes/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 10
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top

  Cannesglow:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list: 
    - https://trakt.tv/users/maxwelldeux/lists/cannes-film-festival-palme-d-or
    - https://trakt.tv/users/sp1ti/lists/cannes-palme-d-or-winners
    letterboxd_list:
    - https://letterboxd.com/connordenney/list/palme-dor/
    - https://letterboxd.com/brsan/list/cannes-palme-dor-winners/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 0
      horizontal_align: left
      vertical_offset: 0
      vertical_align: top

  Venice:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    letterboxd_list:
    - https://letterboxd.com/comfy_fool/list/venice-film-festival-grand-jury-prize-winners/
    - https://letterboxd.com/marco70go/list/venice-film-festival-best-actor-award/
    - https://letterboxd.com/andrewjm/list/volpi-cup-for-best-actress-at-venice-film/
    - https://letterboxd.com/marco70go/list/venice-film-festival-marcello-mastroianni/
    - https://letterboxd.com/neperfectionist/list/golden-lion-leone-doro-winners-of-venice/
    - https://letterboxd.com/moviewithus/list/venice-winners/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 5
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top

  Veniceglow:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list: 
    - https://trakt.tv/users/maxwelldeux/lists/venice-film-festival-golden-lion
    - https://trakt.tv/users/pebao/lists/venice-film-festival_golden-lion
    letterboxd_list:
    - https://letterboxd.com/peterstanley/list/venice-film-festival-golden-lion/
    - https://letterboxd.com/michaelj/list/venice-film-festival-winners-of-the-golden/
    - https://letterboxd.com/eiganerd/list/venice-film-festival-golden-lion/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 0
      horizontal_align: left
      vertical_offset: 0
      vertical_align: top

  Berlin:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    letterboxd_list:
    - https://letterboxd.com/moviewithus/list/berlin-film-festival-winners/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 5
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top

  Berlinglow:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list: 
    - https://trakt.tv/users/maxwelldeux/lists/berlin-international-film-festival-golden-bears
    - https://trakt.tv/users/eloy86/lists/berlin-international-film-festival-golden-bear-winners
    letterboxd_list:
    - https://letterboxd.com/connordenney/list/golden-bear/
    - https://letterboxd.com/socas/list/golden-bear-goldener-bar/
    - https://letterboxd.com/peterstanley/list/berlin-international-film-festival-golden/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 0
      horizontal_align: left
      vertical_offset: 0
      vertical_align: top

  Sundance:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    letterboxd_list:
    - https://letterboxd.com/rads/list/sundance-film-festival-winners/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 10
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top

  Sundanceglow:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list:
    - https://trakt.tv/users/maxwelldeux/lists/sundance-film-festival-grand-jury-prize
    - https://trakt.tv/users/sp1ti/lists/sundance-film-festival-grand-jury-prize-dramatic
    - https://trakt.tv/users/sp1ti/lists/sundance-film-festival-grand-jury-prize-documentary
    letterboxd_list:
    - https://letterboxd.com/josephj/list/sundance-winners/
    - https://letterboxd.com/neperfectionist/list/sundance-film-festival-winners-us-dramatic/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 0
      horizontal_align: left
      vertical_offset: 0
      vertical_align: top

  golden-globe:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    imdb_list: https://www.imdb.com/search/title/?groups=golden_globe_winner
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 5
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top

  golden-globeglow:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list:
    - https://trakt.tv/users/maxwelldeux/lists/golden-globe-award-best-motion-picture
    letterboxd_list:
    - https://letterboxd.com/gabeberk/list/golden-globe-best-motion-picture-winners/
    - https://letterboxd.com/melissaj703/list/golden-globes-best-motion-picture-winners/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 0
      horizontal_align: left
      vertical_offset: 0
      vertical_align: top

  bafta:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    letterboxd_list:
    - https://letterboxd.com/efolds/list/bafta-award-for-best-actress/
    - https://letterboxd.com/rantonucci/list/baftas-best-film-outstanding-british-film/
    - https://letterboxd.com/jonny5244/list/every-bafta-winning-film/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 5
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top

  baftaglow:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list: 
    - https://trakt.tv/users/maxwelldeux/lists/bafta-award-best-film
    - https://trakt.tv/users/ashota/lists/bafta-award-for-best-film
    letterboxd_list:
    - https://letterboxd.com/settingsun/list/all-bafta-award-winners-best-british-film/
    - https://letterboxd.com/trolleyfreak/list/bafta-award-for-best-film-1947/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 0
      horizontal_align: left
      vertical_offset: 0
      vertical_align: top

  saturn:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    letterboxd_list:
    - https://letterboxd.com/jonny5244/list/saturn-awards/
    - https://letterboxd.com/malducin/list/saturn-award-winners-for-best-special-visual/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 5
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top

  saturnglow:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list: 
    - https://trakt.tv/users/eloy86/lists/saturn-award-for-best-science-fiction-film-winners
    letterboxd_list:
    - https://letterboxd.com/elicronier96/list/saturn-award-for-best-science-fiction-movie/
    - https://letterboxd.com/hunterbjork/list/saturn-award-for-best-science-fiction-film/
    - https://letterboxd.com/montyclift/list/saturn-award-winners-for-best-horror-film/
    - https://letterboxd.com/elicronier96/list/saturn-award-for-best-horror-film/
    - https://letterboxd.com/elicronier96/list/saturn-award-for-best-fantasy-film/
    - https://letterboxd.com/elicronier96/list/saturn-award-for-best-action-or-adventure/
    - https://letterboxd.com/fanboycritic/list/best-animated-film-saturn-awards/
    overlay:
      name: <<overlay_name>>
      repo: /Awards-Ratings-Designations/images/<<overlay>>
      group: award
      weight: <<weight>>
      horizontal_offset: 5
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top

overlays:
  Oscarredglow:
    template:
      name: Award
      weight: 100
      imdb_list: https://www.imdb.com/search/title/?groups=oscar_winner
      horizontal_offset: 5
      vertical_offset: 5

  Oscarred:
    template:
      - name: Oscar
        weight: 95

  golden-globeglow:
    template:
      - name: golden-globeglow
        weight: 90 

  golden-globe:
    template:
      - name: golden-globe
        weight: 85

  baftaglow:
    template:
      - name: baftaglow
        weight: 80

  bafta:
    template:
      - name: bafta
        weight: 75

  Palmeredglow:
    template:
      - name: Cannesglow
        weight: 70

  Palmered:
    template:
      - name: Cannes
        weight: 65

  Berlinaleredglow:
    template:
      - name: Berlinglow
        weight: 60

  Berlinalered:
    template:
      - name: Berlin
        weight: 55

  Veniceredglow:
    template:
      - name: Veniceglow
        weight: 50

  Venicered:
    template:
      - name: Venice
        weight: 45

  saturnglow:
    template:
      - name: saturnglow
        weight: 40

  saturn:
    template:
      - name: saturn
        weight: 35

  Sundanceredglow:
    template:
      - name: Sundanceglow
        weight: 30

  Sundancered:
    template:
      - name: Sundance
        weight: 25